; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino

[common]
build_flags =
    -D VERSION=1.0
    -D DEBUG=1
	-D MQTT_MAX_PACKET_SIZE=512

[env:esp32devkit]
platform = espressif32
board = esp32dev
build_flags = 
    ${common.build_flags}
    -DBUZZER_PIN=4
    -DBUZZER_ENABLED=1
    -DACTIVE_BUZZER=0
    -DESP32

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitc-02
board_build.flash_mode = dio
build_flags = 
	${common.build_flags}
	-DBUZZER_PIN=4
	-DBUZZER_ENABLED=1
	-DACTIVE_BUZZER=0
	-DESP32

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
build_flags = 
	${common.build_flags}
	-DBUZZER_PIN=4
	-DBUZZER_ENABLED=1
	-DACTIVE_BUZZER=0


[platformio]
; default_envs = nodemcuv2
default_envs = esp32devkit